on: push
jobs:

  build-arm-template:
    runs-on: ubuntu-latest
    container: node:16
    
    environment:
      name: UAT
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
    
      - name: install and build
        working-directory: ./build
        run: | 
              node --version
              npm --version
              npm install
              npm run build validate ../ /subscriptions/05f19a32-57e6-4417-9d59-5e348bb90a19/resourceGroups/adf-rg/providers/Microsoft.DataFactory/factories/adf-dev-with-git-actions
              npm run build export ../ /subscriptions/05f19a32-57e6-4417-9d59-5e348bb90a19/resourceGroups/adf-rg/providers/Microsoft.DataFactory/factories/adf-dev-with-git-actions armTemplate
             
      - name: Tar artifact
        working-directory: ./build
        run: tar -cvf release_arm_artifact.tar armTemplate
        
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: release_arm_artifact.tar
          path: ./build/armTemplate
          
          
  deploy-arm-template:
    needs: build-arm-template
    runs-on: ubuntu-latest
    
    environment:
      name: UAT
    
    steps:
     - name: Checkout repository
       uses: actions/checkout@v3
       
     - name: Download arm artifact
       uses: actions/download-artifact@v3
       with:
         name: release_arm_artifact.tar
         path: ./arm-template
         
     - name: unzip artifact
       run: | 
         tar cvpfz ./arm-template/release_arm_artifact.tar ./
         cd arm-template
         ls
     
     # install Az PowerShell module
     - name: Install Az PoweShell module
       run: Install-Module -Name Az -Scope CurrentUser -Repository PSGallery -Force 
       shell: pwsh
        
      # Log into Azure
     - name: Log into Azure
       uses: azure/login@v1
       with:
         creds: ${{ secrets.AZ_CREDENTIALS }}
         enable-AzPSSession: true
     
         
   
         
     
              
              
 
