on: push
jobs:
  build-arm-template:
    runs-on: ubuntu-latest
    container: node:16
    steps:
      - name: install utility project
        run: | 
              node --version
              npm --version
