on: push
jobs:
  build-arm-template:
    runs-on: ubuntu-latest
    container: node:16
    environment:
      name: UAT
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
    
      - name: install utility project
        working-directory: ./build
        run: | 
              node --version
              npm --version
              npm install
              npm run build validate 
              
    # ./../subscriptions/05f19a32-57e6-4417-9d59-5e348bb90a19/resourceGroups/adf-rg/providers/Microsoft.DataFactory/factories/adf-dev-with-git-actions 
