on: push
jobs:
  build-arm-template:
    runs-on: ubuntu-latest
    container: node:14
    steps:
      - name: install utility project
        working-directory: ./build
        run: | 
              node --version
              npm --version
